"""add chat_sessions

Revision ID: 4dfedb31a8c1
Revises: 269804b704c9
Create Date: 2025-10-18 19:45:14.690720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dfedb31a8c1'
down_revision: Union[str, Sequence[str], None] = '269804b704c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('locale', sa.String(), server_default=sa.text("'ko-KR'"), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('variables', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_templates'))
    )
    op.create_index('uq_prompt_name_version', 'prompt_templates', ['name', 'version'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('picture_url', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index('idx_chat_sessions_user_time', 'chat_sessions', ['user_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('oauth_identities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'apple', 'kakao', 'naver', name='provider'), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('raw_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_identities')),
    sa.UniqueConstraint('provider', 'subject', name='uq_oauth_provider_subject')
    )
    op.create_table('token_revocations',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_token_revocations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_token_revocations'))
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='input_type'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('card_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model', sa.Enum('gemini_flash', 'gemini_nano', name='model_name'), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('routines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('emotion_target', sa.Enum('calm', 'happy', 'sad', 'angry', 'anxious', 'stressed', 'frustrated', name='emotion'), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('est_minutes', sa.Integer(), nullable=True),
    sa.Column('scientific_basis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('accepted', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_routines_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_routines_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routines'))
    )
    op.create_index('idx_routines_user_time', 'routines', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('inferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('input_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.Enum('gemini_flash', 'gemini_nano', name='model_name'), nullable=False),
    sa.Column('emotion_pred', sa.Enum('calm', 'happy', 'sad', 'angry', 'anxious', 'stressed', 'frustrated', name='emotion'), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('safety_level', sa.Enum('low', 'medium', 'high', 'critical', name='severity'), server_default=sa.text("'low'"), nullable=True),
    sa.Column('retrieved_doc_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['input_id'], ['inputs.id'], name=op.f('fk_inferences_input_id_inputs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_inferences_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inferences'))
    )
    op.create_index('idx_inferences_user_time', 'inferences', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('input_files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('input_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('storage_uri', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['input_id'], ['inputs.id'], name=op.f('fk_input_files_input_id_inputs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_input_files'))
    )
    op.create_table('routine_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('routine_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=False),
    sa.Column('timer_seconds', sa.Integer(), nullable=True),
    sa.Column('checked', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], name=op.f('fk_routine_steps_routine_id_routines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routine_steps'))
    )
    op.add_column('inputs', sa.Column('channel', sa.Enum('text', 'audio', 'image', 'file', name='input_channel'), nullable=False))
    op.add_column('inputs', sa.Column('role', sa.Enum('user', 'assistant', 'system', name='input_type'), nullable=False))
    op.add_column('inputs', sa.Column('text', sa.String(), nullable=True))
    op.add_column('inputs', sa.Column('lang', sa.String(), nullable=True))
    op.add_column('inputs', sa.Column('emotion_hint', sa.Enum('calm', 'happy', 'sad', 'angry', 'anxious', 'stressed', 'frustrated', name='emotion'), nullable=True))
    op.alter_column('inputs', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('inputs', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('inputs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_inputs_session_time', 'inputs', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_inputs_user_time', 'inputs', ['user_id', 'created_at'], unique=False)
    op.create_foreign_key(op.f('fk_inputs_user_id_users'), 'inputs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_inputs_session_id_chat_sessions'), 'inputs', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('inputs', 'modality')
    op.drop_column('inputs', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('inputs', sa.Column('modality', postgresql.ENUM('text', name='modality_enum'), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_inputs_session_id_chat_sessions'), 'inputs', type_='foreignkey')
    op.drop_constraint(op.f('fk_inputs_user_id_users'), 'inputs', type_='foreignkey')
    op.drop_index('idx_inputs_user_time', table_name='inputs')
    op.drop_index('idx_inputs_session_time', table_name='inputs')
    op.alter_column('inputs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('inputs', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('inputs', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('inputs', 'emotion_hint')
    op.drop_column('inputs', 'lang')
    op.drop_column('inputs', 'text')
    op.drop_column('inputs', 'role')
    op.drop_column('inputs', 'channel')
    op.drop_table('routine_steps')
    op.drop_table('input_files')
    op.drop_index('idx_inferences_user_time', table_name='inferences')
    op.drop_table('inferences')
    op.drop_index('idx_routines_user_time', table_name='routines')
    op.drop_table('routines')
    op.drop_table('messages')
    op.drop_table('token_revocations')
    op.drop_table('oauth_identities')
    op.drop_index('idx_chat_sessions_user_time', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('users')
    op.drop_index('uq_prompt_name_version', table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
